---
- hosts: all

  tasks:

  - name: install cpanm into a local::lib
    shell: wget -O- http://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib creates=~/perl5/bin/cpanm

  - name: Set up .profile
    lineinfile: dest=~/.bashrc regexp="^eval `perl -I" line='eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`' state=present

