---
- hosts: chatservers

  vars_prompt:
    bitlbee_pass: "Enter the bitlbee server access password"
    bitlbee_oper_pass: "Enter the bitlbee operator password"

  tasks: 
  
  - name: Install bitlbee package
    apt: pkg=bitlbee state=installed

  - name: Create bitlbee config directory
    file: path=/etc/bitlbee state=directory owner=root group=root mode=0755
  
  - name: Create bitlbee state directory
    file: path=/var/run/bitlbee state=directory owner=bitlbee group=bitlbee mode=0700

  - name: Install bitlbee config file
    template: src=templates/bitlbee-conf.j2 dest=/etc/bitlbee/bitlbee.conf owner=root group=root mode=0644
    notify: restart bitlbee
  
  - name: Install bitlbee MOTD file
    copy: src=config/bitlbee-motd.txt dest=/etc/bitlbee/motd.txt owner=root group=root mode=0644
    notify: restart bitlbee

  - name: Run bitlbee service
    service: name=bitlbee enabled=yes state=started

  handlers:
  
  - name: restart bitlbee
    service: name=bitlbee state=restarted
